### ISSUE TITLE
Consider using psr/http-client instead of apimatic

### ISSUE THREAD

**Issue by pkly** [paypal/PayPal-PHP-Server-SDK#13]
Hello, I've noticed this library uses https://packagist.org/packages/apimatic/unirest-php for it's http client, instead of the widely adopted  https://packagist.org/packages/psr/http-client.
As psr/http-client is way more popular (about 453 million more downloads overall) and is a widely recognized standard implemented by basically every framework natively, there's no reason for using apimatic for this library.
As of this post apimatic does not even claim to support php 8.3, a version from over a year ago.
I would like you to reconsider your approach, as fragmentation is not something the php ecosystem needs, and psr's interface is extremely easy to use.

**Comment by LeonarthusMectus** [comment]
Hey @pkly

We'd like to understand the concern a bit better and are curious what the primary motivation would be here.  
* Is there a specific benefit to you as a consumer of the SDK gained from using one of the proposed HTTP libs?  
* Are you experiencing issues related to the usage of the current HTTP lib?
* Would you just prefer it use the more popular/common alternative?

**Comment by pkly** [comment]
Of course, here's the reasoning:

- psr/http-client is a widely available implementation, with major frameworks already bundling it in (eg. Symfony)
- as such, in these frameworks, only using these clients (as they need to be decorated), any http calls can be debugged and seen by the application in a profiler, which helps in development
In our case, I had to write a custom implementation for a library called omnipay just so we could see requests to payment libraries in our application at all, if you go along with apimatic, we'd need to do the same again, just to see what we're sending and when, which is useful
- psr's interfaces do the job we need already in a standardized manner, with a more mature ecosystem of libraries which provide the features you need
https://packagist.org/providers/psr/http-factory-implementation
https://packagist.org/providers/psr/http-message-implementation
https://packagist.org/providers/psr/http-client-implementation
- this way, this library would only need to require the `psr/http-client`, `psr/http-message`, `psr/http-factory` (and optionally, but probably recommended `php-http/discovery`) packages, with only any implementations added in require-dev for testing purposes, and all the actual implementations could be wired in from a framework like so (example from one of our libraries in Symfony)

```yaml
services:
  YourLib\RequestBuilder:
    arguments:
      $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
      $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'
      $uriFactory: '@Psr\Http\Message\UriFactoryInterface'

  YourLib\Client:
    arguments:
      $builder: '@YourLib\RequestBuilder'
      $client: '@Psr\Http\Client\ClientInterface'
      $options:
        some_option: 'some_value'
```

Where the `RequestBuilder` is a class that simplifies creating a single `RequestInterface` from "normal" options like method, url, query, request, headers, etc.
Additionally I was sure I saw a `<8.2` on php limitation for one of the packages you use, but it seems to not be the case, now that I checked again? I'm unsure about that, seems like it'd work in newer versions of php at least. But still, popularity alone is a point against it, as the unirest-php library seems to depend on curl for it's requests, where as the other libraries may provide any implementation. The api itself seems to be somewhat similar, so likely re-working your code wouldn't be that hard.

And as @8ctopus said above, PSR-17 is `psr/http-factory` and PSR-7 is `psr/http-message`, as you'd need a client you also need PSR-18 - `psr/http-client`
